baseURL = "https://arthurmolendowski.github.io/"
copyright = "© 2026 Artur Molendowski"
defaultContentLanguage = "pl"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "pl"
timeZone = "Europe/Warsaw"
timeout = "120s"
title = "Artur Molendowski | Portfolio"

[params]
  defaultTheme = "dark"
  description = "Portfolio fotograficzne Artura Molendowskiego"
  title = "Artur Molendowski"
  
  [params.author]
    email = "twoj@email.com" # WPISZ SWÓJ EMAIL
    name = "Artur Molendowski"

  [params.socialIcons]
    # facebook = "https://www.facebook.com/"
    # instagram = "https://www.instagram.com/"
    email = "mailto:twoj@email.com"

  [params.gallery]
    boxSpacing = 10
    targetRowHeight = 288

[outputs]
  home = ["HTML"] # Zostawiłem tylko HTML, żeby uniknąć błędu z XML
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 85
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    name = "Kontakt"
    url = "mailto:twoj@email.com"
    weight = 3
    
  [[menu.main]]
    name = "Projekt 365 - Tookapic"
    url = "https://tookapic.com/snufkin_artur"
    weight = 4
    categories: ["Projekt 365 - Tookapic"]
